// Copyright 2024 xgfone
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package op

import "strings"

// Pre-define some operations.
var (
	KeyId     = Key("id")
	KeyUserId = Key("user_id")
	KeyOpenId = Key("open_id")
	KeyTaskId = Key("task_id")
	KeyAddrId = Key("addr_id")

	KeyOrderId  = Key("order_id")
	KeyTransId  = Key("trans_id")
	KeyCouponId = Key("coupon_id")

	KeyTmplId  = Key("tmpl_id")
	KeyModelId = Key("model_id")
	KeyCoverId = Key("cover_id")
	KeyImageId = Key("image_id")
	KeyPhotoId = Key("photo_id")
	KeyAudioId = Key("audio_id")
	KeyMusicId = Key("music_id")
	KeyVideoId = Key("video_id")
	KeyStyleId = Key("style_id")

	KeyUnionId     = Key("union_id")
	KeyGroupId     = Key("group_id")
	KeyMemberId    = Key("member_id")
	KeyInviterId   = Key("inviter_id")
	KeyInviterCode = Key("inviter_code")

	KeyClientId = Key("client_id")
	KeyServerId = Key("server_id")

	KeyItemId   = Key("item_id")
	KeyItemType = Key("item_type")

	KeyTaskerId   = Key("tasker_id")
	KeyTaskerUrl  = Key("tasker_url")
	KeyTaskerAddr = Key("tasker_addr")
	KeyTaskerInfo = Key("tasker_info")
	KeyTaskerType = Key("tasker_type")

	KeyOpCode = Key("op_code")
	KeyOpData = Key("op_data")
	KeyOpType = Key("op_type")
	KeyOpInfo = Key("op_info")
	KeyOpNote = Key("op_note")

	KeyAge  = Key("age")
	KeyArg  = Key("arg")
	KeyApp  = Key("app")
	KeyDay  = Key("day")
	KeyNum  = Key("num")
	KeySrc  = Key("src")
	KeyDst  = Key("dst")
	KeyKey  = Key("key")
	KeyOff  = Key("off")
	KeyTmb  = Key("tmb")
	KeyTag  = Key("tag")
	KeyTags = Key("tags")
	KeyArea = Key("area")
	KeyZone = Key("zone")
	KeyPath = Key("path")
	KeyAuth = Key("auth")
	KeyAbbr = Key("abbr")
	KeyAddr = Key("addr")
	KeyCity = Key("city")
	KeyName = Key("name")
	KeyNick = Key("nick")
	KeyNote = Key("note")
	KeyDesc = Key("desc")
	KeyCode = Key("code")
	KeyConf = Key("conf")
	KeyCost = Key("cost")
	KeyData = Key("data")
	KeyDate = Key("date")
	KeyTime = Key("time")
	KeySort = Key("sort")
	KeyType = Key("type")
	KeyStep = Key("step")
	KeyFlag = Key("flag")
	KeyFrom = Key("from")
	KeyOmit = Key("omit")
	KeyRead = Key("read")
	KeySign = Key("sign")
	KeyTmpl = Key("tmpl")
	KeyArgs = Key("args")
	KeyShop = Key("shop")
	KeyKind = Key("kind")
	KeyNext = Key("next")

	KeySize  = Key("size")
	KeyUsed  = Key("used")
	KeyRest  = Key("rest")
	KeyRate  = Key("rate")
	KeyAvail = Key("avail")
	KeyCount = Key("count")
	KeyLimit = Key("limit")
	KeyTotal = Key("total")
	KeyValue = Key("value")
	KeyIndex = Key("index")
	KeyGroup = Key("group")
	KeyPrint = Key("print")
	KeyScore = Key("score")

	KeyBless = Key("bless")
	KeyStyle = Key("style")
	KeyTitle = Key("title")
	KeyCover = Key("cover")
	KeyImage = Key("image")
	KeyPhoto = Key("photo")
	KeyMusic = Key("music")
	KeyVideo = Key("video")
	KeyModel = Key("model")
	KeyAudio = Key("audio")
	KeyLyric = Key("lyric")
	KeyTheme = Key("theme")
	KeyScene = Key("scene")
	KeyPaper = Key("paper")

	KeyTmplUrl = Key("tmpl_url")
	KeyOrigUrl = Key("orig_url")
	KeyMarkUrl = Key("mark_url")
	KeyTmbnUrl = Key("tmbn_url")
	KeyTmbUrl  = Key("tmb_url")
	KeyMaxUrl  = Key("max_url")
	KeyBgUrl   = Key("bg_url")

	KeyCoverUrl = Key("cover_url")
	KeyImageUrl = Key("image_url")
	KeyPhotoUrl = Key("photo_url")
	KeyAudioUrl = Key("audio_url")
	KeyMusicUrl = Key("music_url")
	KeyVideoUrl = Key("video_url")

	KeyClientUrl  = Key("client_url")
	KeyServerUrl  = Key("server_url")
	KeyClientAddr = Key("client_addr")
	KeyServerAddr = Key("server_addr")

	KeyIp     = Key("ip")
	KeyNet    = Key("net")
	KeyUrl    = Key("url")
	KeyCidr   = Key("cidr")
	KeyHost   = Key("host")
	KeyPort   = Key("port")
	KeyScheme = Key("scheme")
	KeyMethod = Key("method")
	KeySource = Key("source")
	KeyTarget = Key("target")
	KeyClient = Key("client")
	KeyServer = Key("servet")
	KeyCensor = Key("censor")
	KeyOrigin = Key("origin")
	KeyAction = Key("action")
	KeyGlobal = Key("global")

	KeyOrder   = Key("order")
	KeyPrice   = Key("price")
	KeyAmount  = Key("amount")
	KeyCoupon  = Key("coupon")
	KeyNumber  = Key("number")
	KeyBalance = Key("balance")
	KeyStorage = Key("storage")
	KeyIllegal = Key("illegal")
	KeyFailure = Key("failure")
	KeySuccess = Key("success")
	KeyResult  = Key("result")

	KeyOffline = Key("offline")
	KeyOnline  = Key("online")

	KeyPrize     = Key("prize")
	KeyPrizeCode = Key("prize_code")
	KeyPrizeData = Key("prize_data")
	KeyPrizeInfo = Key("prize_info")
	KeyPrizeType = Key("prize_type")

	KeyDiscount    = Key("discount")
	KeyPayType     = Key("pay_type")
	KeyPayInfo     = Key("pay_info")
	KeyPayData     = Key("pay_data")
	KeyPayConf     = Key("pay_conf")
	KeyPayPrice    = Key("pay_price")
	KeyPayAmount   = Key("pay_amount")
	KeyPaidAmount  = Key("paid_amount")
	KeyTransAmount = Key("trans_amount")
	KeyTransDesc   = Key("trans_desc")
	KeyTransData   = Key("trans_data")
	KeyTransInfo   = Key("trans_info")
	KeyTransNote   = Key("trans_note")
	KeyTransType   = Key("trans_type")
	KeyUnitPrice   = Key("unit_price")
	KeyOrigPrice   = Key("orig_price")
	KeyOffPrice    = Key("off_price")

	KeyPay     = Key("pay")
	KeyPaid    = Key("paid")
	KeyNotPay  = Key("notpay")
	KeyNeedPay = Key("needpay")

	KeyPType       = Key("ptype")
	KeyPData       = Key("pdata")
	KeyPConf       = Key("pconf")
	KeyProductType = Key("product_type")
	KeyProductData = Key("product_data")
	KeyProductConf = Key("product_conf")

	KeyScale    = Key("scale")
	KeyWidth    = Key("width")
	KeyHeight   = Key("height")
	KeyWeight   = Key("weight")
	KeyPreview  = Key("preview")
	KeyHorizon  = Key("horizon")
	KeyVertical = Key("vertical")
	KeyTemplate = Key("template")

	KeyPrompt         = Key("prompt")
	KeyNPrompt        = Key("nprompt")
	KeyPosPrompt      = Key("pos_prompt")
	KeyNegPrompt      = Key("neg_prompt")
	KeyPositivePrompt = Key("positive_prompt")
	KeyNegativePrompt = Key("negative_prompt")

	KeyVotes   = Key("votes")
	KeyVoted   = Key("voted")
	KeyIsVoted = Key("is_voted")
	KeyVotedAt = Key("voted_at")

	KeyCard   = Key("card")
	KeyCardNo = Key("card_no")
	KeyCardId = Key("card_id")

	KeyAK       = Key("ak")
	KeySK       = Key("sk")
	KeyDeny     = Key("deny")
	KeyAllow    = Key("allow")
	KeyBrand    = Key("brand")
	KeyBirth    = Key("birth")
	KeyGrade    = Key("grade")
	KeyAlias    = Key("alias")
	KeyAppid    = Key("appid")
	KeyEmail    = Key("email")
	KeyPhone    = Key("phone")
	KeyMobile   = Key("mobile")
	KeyGender   = Key("gender")
	KeyRegion   = Key("region")
	KeyConfig   = Key("config")
	KeyAvatar   = Key("avatar")
	KeyApiKey   = Key("apikey")
	KeyPubKey   = Key("pubkey")
	KeyPriKey   = Key("prikey")
	KeySecret   = Key("secret")
	KeyStreet   = Key("street")
	KeyQrCode   = Key("qrcode")
	KeyAliases  = Key("aliases")
	KeyChannel  = Key("channel")
	KeyContact  = Key("contact")
	KeyAddress  = Key("address")
	KeyCountry  = Key("country")
	KeyProvince = Key("province")
	KeyDistrict = Key("district")
	KeyPosition = Key("position")
	KeyUsername = Key("username")
	KeyPassword = Key("password")
	KeyBirthday = Key("birthday")
	KeyAbnormal = Key("abnormal")
	KeySerialNo = Key("serial_no")
	KeyUserType = Key("user_type")
	KeyUserKind = Key("user_kind")
	KeyUserInfo = Key("user_info")
	KeyUserData = Key("user_data")

	KeyMachine     = Key("machine")
	KeyMachineId   = Key("machine_id")
	KeyMachineCode = Key("machine_code")

	KeyAnswer     = Key("answer")
	KeyAnswerId   = Key("answer_id")
	KeyQuestion   = Key("question")
	KeyQuestionId = Key("question_id")

	KeyCbAt   = Key("cb_at")
	KeyCbUrl  = Key("cb_url")
	KeyCbCode = Key("cb_code")
	KeyCbData = Key("cb_data")
	KeyCbInfo = Key("cb_info")
	KeyCbType = Key("cb_type")

	KeySvcId   = Key("svc_id")
	KeySvcUrl  = Key("svc_url")
	KeySvcAddr = Key("svc_addr")
	KeySvcCode = Key("svc_code")
	KeySvcData = Key("svc_data")
	KeySvcInfo = Key("svc_info")
	KeySvcType = Key("svc_type")

	KeyEvent    = Key("event")
	KeyReason   = Key("reason")
	KeyStatus   = Key("status")
	KeyRemain   = Key("remain")
	KeySecond   = Key("second")
	KeyPercent  = Key("percent")
	KeyVersion  = Key("version")
	KeySeconds  = Key("seconds")
	KeyTrigger  = Key("trigger")
	KeyInterval = Key("interval")
	KeyCallback = Key("callback")

	KeyIsShow     = Key("is_show")
	KeyIsHidden   = Key("is_hidden")
	KeyIsEnabled  = Key("is_enabled")
	KeyIsDisabled = Key("is_disabled")

	KeyTmplData = Key("tmpl_data")
	KeyTmplConf = Key("tmpl_conf")
	KeyTmplInfo = Key("tmpl_info")
	KeyTmplType = Key("tmpl_type")

	KeyTaskAt   = Key("task_at")
	KeyTaskName = Key("task_name")
	KeyTaskInfo = Key("task_info")
	KeyTaskData = Key("task_data")
	KeyTaskType = Key("task_type")

	KeyReqName = Key("req_name")
	KeyReqBody = Key("req_body")
	KeyReqInfo = Key("req_info")
	KeyReqData = Key("req_data")
	KeyReqType = Key("req_type")

	KeyResCode = Key("res_code")
	KeyResBody = Key("res_body")
	KeyResInfo = Key("res_info")
	KeyResData = Key("res_data")
	KeyResType = Key("res_type")

	KeyEndAt     = Key("end_at")
	KeyGotAt     = Key("got_at")
	KeyPubAt     = Key("pub_at")
	KeySubAt     = Key("sub_at")
	KeyDoneAt    = Key("done_at")
	KeySchdAt    = Key("schd_at")
	KeyPaidAt    = Key("paid_at")
	KeyStartAt   = Key("start_at")
	KeyRefundAt  = Key("refund_at")
	KeyCreatedAt = Key("created_at")
	KeyUpdatedAt = Key("updated_at")
	KeyDeletedAt = Key("deleted_at")
	KeyExpiredAt = Key("expired_at")
	KeyTriggerAt = Key("trigger_at")

	KeyRegisterAt = Key("register_at")
)

// Pre-define some field condition operations.
var (
	IsDeletedCond    = KeyDeletedAt.NotEq("0000-00-00 00:00:00")
	IsNotDeletedCond = KeyDeletedAt.Eq("0000-00-00 00:00:00")
)

// IsNotDeletedCondWithTable returns a condition operation that is not deleted
// with table prefix.
func IsNotDeletedCondWithTable(table string) Condition {
	op := IsNotDeletedCond.Op()
	key := strings.Join([]string{table, op.Key}, Sep)
	return op.WithKey(key).Condition()
}
